[book]
title = "C++ to Rust Phrasebook 中文"
authors = ["Cognitive Engineering Lab"]
language = "zh-CN"
translator = "Xiangong Tang"
description = "一本帮助将 C++ 常见用法转换为 Rust 的书籍。"
multilingual = false
src = "src"


[output.html]
additional-css = ["custom.css"]
additional-js = ["telemetry/dist/telemetry.iife.js"]
code.hidelines = { cpp = "$" }
fold.enable = true
fold.level = 1
site-url = "https://tangxiangong.github.io/crp-zh/"
git-repository-url = "https://github.com/tangxiangong/crp-zh"

[preprocessor.quiz]
initial-text = "Check your understanding"
fullscreen = true

# [output.linkcheck]
